### ISSUE TITLE
YAML Manifest as easier default that Python

### ISSUE THREAD

**Issue by thomas-anderson-bsl** [brightsparklabs/appcli#21]
Most of the default python cli script can be expressed as a set of variables that could be defined as a YAML file. This should support only the simple cases of appcli usage (i.e. no hooks or other custom Python)

For example, we would like to be able to define a simple appcli application with the following YAML file:

```yaml
app_name: "myapp"
docker_image: "brightsparklabs/myapp"
seed_app_configuration_file: "resources/settings.yml"
baseline_templates_dir: "resources/templates/baseline"
configurable_templates_dir: "resource/templates/configurable:
orchestrator:
    type: "DockerComposeOrchestrator"
    config:
        compose_file: "docker-compose.yml"
mandatory_additional_data_dirs:
    - "EXTRA_DATA"
mandatory_additional_env_variables:
    - "ENV_VAR_2"
```
